name    'alkivi-ups'
version '0.0.2'
source 'https://github.com/alkivi-sas/puppet-ups'
author 'alkivi'
license 'LGPLv3'
summary 'Controls NUT server and client'
description 'Setup NUT server and client to handle UPS in puppet'
project_page 'https://github.com/alkivi-sas/puppet-ups'
dependency 'puppetlabs/stdlib', '>3.x'
#dependency 'puppetlabs/concat', '1.0.0'
#dependency 'puppetlabs/apache', '>0.x'
dependency 'alkivi/alkivi_base', '>0.x'
